version: '3.7'
services:
    all-in-one:
        container_name: all-in-one
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        build:
            context: ./
    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    caddy:
        image: caddy/caddy:2.2.1-alpine
        container_name: caddy-service
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/srv
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
